float32 intemp              # indoor temperature in °C
float32 inhumi              # indoor humidity in %
float32 abspress            # absolute pressure in mbar
float32 relpress            # relative pressure in mbar
float32 outtemp             # outdoor temperature in °C
float32 outhumi             # outdoor humidity in %
float32 windir              # wind direction in °
float32 windspeed           # wind speed in km/h
float32 gustspeed
float32 solarrad            # solar radiation in w/m2   
float32 uv                  # UV 
float32 uvi                 # UV index 
float32 rainofhourly        # rainfall in mm per hour